plugins { id 'com.android.application' }

android {
    namespace 'br.com.luan.fichalivre'
    compileSdk 35

    defaultConfig {
        applicationId 'br.com.luan.fichalivre'
        minSdk 26
        targetSdk 35
        versionCode 34
        versionName '3.4'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
