from pathlib import Path
p=Path('app/src/main/assets/Ficha.html')
s=p.read_text(encoding='utf-8')
s=s.replace('Versão instalada: <b>2.2</b> · base limpa do app original','Versão instalada: <b>2.3</b> · cálculos automáticos de progressão').replace("const APP_VERSION='2.2';","const APP_VERSION='2.3';")
css='''\n.progression-config{margin-top:14px;padding:14px;border:1px solid var(--line);border-radius:11px;background:color-mix(in srgb,var(--sheet-color) 58%,transparent)}.progression-config h3{margin:0 0 10px;font-size:13px}.progression-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.progression-grid input{text-align:center;font-size:18px}.progression-budget{margin-top:8px;font-size:11px;color:var(--sheet-accent);font-weight:700}#irregularBaseBox{margin-top:13px;padding-top:12px;border-top:1px solid var(--line)}input.derived{opacity:.86;cursor:default;background:color-mix(in srgb,var(--sheet-accent) 8%,transparent)}\n'''
s=s.replace('</style></head>',css+'</style></head>',1)
needle='<details class="sheet-help"><summary>Sobre a classe</summary><p id="classInfo"></p></details></section><section class="card"><div class="heading"><div><div class="eyebrow">Essência</div><h2>Atributos</h2></div>'
ui='''<details class="sheet-help"><summary>Sobre a classe</summary><p id="classInfo"></p></details><div class="progression-config"><h3>Progressão de PV e PE</h3><div class="progression-grid"><label>PV por nível<input id="hpGain" type="number" min="0" max="4" inputmode="numeric"></label><label>PE por nível<input id="epGain" type="number" min="0" max="4" inputmode="numeric"></label></div><div class="progression-budget" id="growthBudget">4 / 4 pontos por nível</div><div id="irregularBaseBox"><div class="hint">Irregular: distribua os 18 pontos iniciais entre PV e PE.</div><div class="progression-grid" style="margin-top:8px"><label>PV base<input id="irregularHpBase" type="number" min="0" max="18" inputmode="numeric"></label><label>PE base<input id="irregularEpBase" type="number" min="0" max="18" inputmode="numeric"></label></div><div class="progression-budget" id="irregularBaseBudget">18 / 18 pontos iniciais</div></div></div></section><section class="card"><div class="heading"><div><div class="eyebrow">Essência</div><h2>Atributos</h2></div>'''
assert needle in s
s=s.replace(needle,ui,1)
s=s.replace('<input id="hpMax" type="number" min="0" aria-label="PV máximo">','<input id="hpMax" class="derived" type="number" min="0" aria-label="PV máximo" readonly>')
s=s.replace('<input id="epMax" type="number" min="0" aria-label="PE máximo">','<input id="epMax" class="derived" type="number" min="0" aria-label="PE máximo" readonly>')
s=s.replace('<label>C.A.<input id="ca" type="number"></label>','<label>C.A. <span class="hint">automática</span><input id="ca" class="derived" type="number" readonly></label>')
s=s.replace('<label>MS<input id="ms" type="number" step="0.5"></label>','<label>MS <span class="hint">automático</span><input id="ms" class="derived" type="number" step="0.5" readonly></label>')
s=s.replace('Todas as classes recebem 4 pontos por nível para distribuir entre PV/PE. A contagem de níveis que concede esse aumento permanece manual.','Todas as classes recebem 4 pontos por nível para distribuir entre PV/PE. O nível 1 usa a base; do nível 2 em diante o ganho escolhido é aplicado automaticamente.')
s=s.replace('PV, PE, C.A., MS, redução de dano e bônus de classe ficam manuais. DT passiva é um registro, sem efeito automático sobre dados.','PV/PE máximos, C.A. e MS são calculados automaticamente por atributos, classe, nível e progressão. PV/PE atuais e redução de dano continuam editáveis. DT passiva é um registro, sem efeito automático sobre dados.')
js=r'''
/* v2.3 derived stats */
const __blank22=blank;blank=function(){const c=__blank22();c.hpGain=2;c.epGain=2;c.irregularHpBase=9;c.irregularEpBase=9;return c};
const __upgrade22=upgrade;upgrade=function(c){__upgrade22(c);if(!Number.isInteger(c.hpGain))c.hpGain=2;if(!Number.isInteger(c.epGain))c.epGain=4-c.hpGain;if(c.hpGain+c.epGain!==4){c.hpGain=2;c.epGain=2}if(!Number.isInteger(c.irregularHpBase))c.irregularHpBase=9;if(!Number.isInteger(c.irregularEpBase))c.irregularEpBase=18-c.irregularHpBase;if(c.irregularHpBase+c.irregularEpBase!==18){c.irregularHpBase=9;c.irregularEpBase=9}return c};
function v23clamp(n,a,b){n=Math.trunc(Number(n));return Number.isFinite(n)?Math.max(a,Math.min(b,n)):a}
function v23derive(c){upgrade(c);const L=v23clamp(c.level,1,99999),fis=v23clamp(c.attrs.FIS,1,20),des=v23clamp(c.attrs.DES,1,20),intel=v23clamp(c.attrs.INT,1,20);let hb,eb;if(c.class==='Irregular'){hb=c.irregularHpBase;eb=c.irregularEpBase}else{[hb,eb]=({Colosso:[12,6],Combatente:[10,8],Especialista:[9,9]}[c.class]||[9,9])}c.hpMax=hb+fis+(L-1)*c.hpGain;c.epMax=eb+intel+(L-1)*c.epGain;const bonus=c.class==='Combatente'?2:c.class==='Colosso'?1:0;c.ca=Math.min(c.class==='Combatente'?17:15,10+mod(des)+bonus);c.ms=8+mod(des)+(c.class==='Especialista'?2:0);return c}
function v23progress(){const c=v23derive(char());$('#hpGain').value=c.hpGain;$('#epGain').value=c.epGain;$('#growthBudget').textContent=`${c.hpGain+c.epGain} / 4 pontos por nível · nível ${c.level}`;$('#irregularBaseBox').hidden=c.class!=='Irregular';$('#irregularHpBase').value=c.irregularHpBase;$('#irregularEpBase').value=c.irregularEpBase;$('#irregularBaseBudget').textContent=`${c.irregularHpBase+c.irregularEpBase} / 18 pontos iniciais`;$('#classInfo').textContent=CLASSES[c.class]+' PV/PE máximos, C.A. e MS são automáticos.'}
const __resources22=renderResources;renderResources=function(){const c=v23derive(char());$('#hpMax').value=c.hpMax;$('#epMax').value=c.epMax;$('#ca').value=c.ca;$('#ms').value=c.ms;v23progress();return __resources22()};
const __render22=render;render=function(){v23derive(char());const r=__render22();v23progress();renderResources();return r};
$('#attrs').addEventListener('input',e=>{if(e.target.dataset.attr){renderResources();changed()}});
function v23pair(id,key,other,otherKey,total){$('#'+id).addEventListener('input',e=>{if(e.target.value==='')return;const c=char(),v=v23clamp(e.target.value,0,total);c[key]=v;c[otherKey]=total-v;renderResources();changed()});$('#'+id).addEventListener('blur',v23progress)}
v23pair('hpGain','hpGain','epGain','epGain',4);v23pair('epGain','epGain','hpGain','hpGain',4);v23pair('irregularHpBase','irregularHpBase','irregularEpBase','irregularEpBase',18);v23pair('irregularEpBase','irregularEpBase','irregularHpBase','irregularHpBase',18);
const __validate22=validate;validate=function(raw){const c=__validate22(raw),x=raw.character||{};for(const [k,m,d] of [['hpGain',4,2],['epGain',4,2],['irregularHpBase',18,9],['irregularEpBase',18,9]])if(x[k]!==undefined)c[k]=Number.isInteger(x[k])&&x[k]>=0&&x[k]<=m?x[k]:d;if(c.hpGain+c.epGain!==4){c.hpGain=2;c.epGain=2}if(c.irregularHpBase+c.irregularEpBase!==18){c.irregularHpBase=9;c.irregularEpBase=9}return v23derive(c)};
'''
marker="window.addEventListener('beforeunload'"
assert marker in s
s=s.replace(marker,js+'\n'+marker,1)
assert "const APP_VERSION='2.3'" in s and 'id="hpGain"' in s and 'v23derive' in s
p.write_text(s,encoding='utf-8')
